version: "3.3"
services:
  airlines:
    build: "./airlines"
    ports:
      - "3000:3001"
    environment:
      PORT: 3001

  airports:
    build: "./airports"
    ports:
      - "3001:3002"
    environment:
      PORT: 3002

  flights:
    build: "./flights"
    ports:
      - "3002:3003"
    environment:
      PORT: 3003

  planes:
    build: "./planes"
    ports:
      - "3003:3004"
    environment:
      PORT: 3004
